-- Run only in a disposable staging project with canonical exchange fixtures.
-- Every fixture change, session and administrator grant is rolled back.
begin;
do $$
declare a uuid; m uuid; sid uuid:=extensions.gen_random_uuid(); mid uuid:=extensions.gen_random_uuid();
  rid uuid:=extensions.gen_random_uuid(); case_id uuid; support_id uuid; set_id text; rev integer; result jsonb; original_state text;
begin
  select id into a from public.profiles order by created_at,id limit 1;
  select id into m from public.profiles where id<>a order by created_at,id limit 1;
  if a is null or m is null then raise exception 'Staging requires two disposable profiles'; end if;
  insert into auth.sessions(id,user_id,created_at,updated_at) values(sid,a,now(),now()),(mid,m,now(),now());
  insert into private.exchange_admins(user_id) values(a) on conflict do nothing;
  delete from private.exchange_admins where user_id=m;
  assert not has_function_privilege('anon','public.admin_marketplace_read(text,text,integer,text)','EXECUTE');
  assert not has_function_privilege('anon','public.admin_marketplace_mutate(text,text,text,integer,text,uuid)','EXECUTE');
  assert not has_table_privilege('authenticated','private.marketplace_admin_audit','SELECT');
  assert not has_table_privilege('authenticated','private.marketplace_admin_revisions','UPDATE');
  perform set_config('request.jwt.claims',jsonb_build_object('sub',m,'role','authenticated','session_id',mid,'user_metadata',jsonb_build_object('admin',true))::text,true);
  begin perform public.admin_marketplace_read(); raise exception 'Member read unexpectedly allowed'; exception when insufficient_privilege then null; end;
  begin perform public.admin_marketplace_mutate('catalogue','invalid','hidden',0,'Unsafe forged admin',rid); raise exception 'Member write unexpectedly allowed'; exception when insufficient_privilege then null; end;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated','session_id',sid,'aal','aal1')::text,true);
  begin perform public.admin_marketplace_read(); raise exception 'Single factor admin allowed'; exception when sqlstate 'PT403' then null; end;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated','session_id',sid,'aal','aal2')::text,true);
  result:=public.admin_marketplace_read();
  assert (result->'summary'->>'members')::bigint=(select count(*) from public.profiles);
  assert (result->'summary'->>'exchanges')::bigint=(select count(*) from public.exchange_cases);
  result:=public.admin_marketplace_read('members','',0);
  assert jsonb_array_length(result->'rows')=least(25,(select count(*) from public.profiles));
  result:=public.admin_marketplace_read('members','',1);
  assert jsonb_array_length(result->'rows')=least(25,greatest(0,(select count(*) from public.profiles)-25));
  perform public.admin_marketplace_read('member_detail','',0,a::text);
  perform public.admin_marketplace_read('catalogue');
  perform public.admin_marketplace_read('exchanges');
  perform public.admin_marketplace_read('support');
  perform public.admin_marketplace_read('audit');
  begin perform public.admin_marketplace_read('auth_users'); raise exception 'Unknown section allowed'; exception when invalid_parameter_value then null; end;
  select set_number into set_id from public.lego_sets order by set_number limit 1;
  if set_id is null then raise exception 'Staging requires one catalogue set'; end if;
  select coalesce((select revision from private.marketplace_admin_revisions where entity_type='catalogue' and entity_id=set_id),0) into rev;
  result:=public.admin_marketplace_mutate('catalogue',set_id,'hidden',rev,'Staging visibility test',rid);
  assert (result->>'revision')::int=rev+1;
  assert not (select catalog_active from public.lego_sets where set_number=set_id);
  result:=public.admin_marketplace_mutate('catalogue',set_id,'hidden',rev,'Staging visibility test',rid);
  assert (result->>'replayed')::boolean;
  assert (select count(*) from private.marketplace_admin_audit where actor_id=a and request_id=rid)=1;
  begin perform public.admin_marketplace_mutate('catalogue',set_id,'visible',rev,'Staging visibility test',rid); raise exception 'Changed replay allowed'; exception when serialization_failure then null; end;
  begin perform public.admin_marketplace_mutate('catalogue',set_id,'visible',rev,'Staging visibility test',extensions.gen_random_uuid()); raise exception 'Stale revision allowed'; exception when serialization_failure then null; end;
  begin perform public.admin_marketplace_mutate('catalogue',set_id,'delete',rev+1,'Staging invalid test',extensions.gen_random_uuid()); raise exception 'Delete allowed'; exception when invalid_parameter_value then null; end;
  begin perform public.admin_marketplace_mutate('catalogue',set_id,'visible',rev+1,'short',extensions.gen_random_uuid()); raise exception 'Short reason allowed'; exception when invalid_parameter_value then null; end;
  select id,state into case_id,original_state from public.exchange_cases order by created_at,id limit 1;
  if case_id is null then raise exception 'Staging requires one exchange fixture'; end if;
  perform public.admin_marketplace_read('exchange_detail','',0,case_id::text);
  insert into public.exchange_case_support_requests(case_id,requested_by,category,note,case_state_at_request,case_state_version_at_request,idempotency_key)
    select id,user_a,'other','Staging admin test',state,state_version,extensions.gen_random_uuid()::text from public.exchange_cases where id=case_id returning id into support_id;
  result:=public.admin_marketplace_mutate('support',support_id::text,'in_progress',0,'Reviewing collector request',extensions.gen_random_uuid());
  assert (result->>'revision')::int=1;
  result:=public.admin_marketplace_read('support',support_id::text);
  assert result->'rows'->0->>'status'='in_progress';
  perform public.admin_marketplace_mutate('support',support_id::text,'resolved',1,'Support guidance provided',extensions.gen_random_uuid());
  assert (select state from public.exchange_cases where id=case_id)=original_state;
  assert (select closed_at from public.exchange_case_support_requests where id=support_id) is null;
  update auth.sessions set not_after=now()-interval '1 second' where id=sid;
  begin perform public.admin_marketplace_read(); raise exception 'Expired session allowed'; exception when insufficient_privilege then null; end;
  update auth.sessions set not_after=null where id=sid;
  delete from auth.sessions where id=sid;
  begin perform public.admin_marketplace_read(); raise exception 'Revoked session allowed'; exception when insufficient_privilege then null; end;
  insert into auth.sessions(id,user_id) values(sid,a);
  delete from private.exchange_admins where user_id=a;
  begin perform public.admin_marketplace_read(); raise exception 'Revoked admin allowed'; exception when insufficient_privilege then null; end;
end;
$$;
rollback;
