-- BrickCircle V2.1 production schema. Run once in Supabase SQL Editor.
create extension if not exists pgcrypto;

create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, username text unique, display_name text not null default '', email text, country text, city text, bio text default '', avatar_url text, rating numeric(3,2) default 5.00, review_count integer default 0, trust_score integer default 50 check(trust_score between 0 and 100), email_verified boolean default false, identity_verified boolean default false, address_verified boolean default false, mfa_enabled boolean default false, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.exchange_preferences (user_id uuid primary key references public.profiles(id) on delete cascade, international boolean default true, max_value numeric(12,2) default 1000, shipping_method text default 'tracked', durations integer[] default array[30,60,90], themes text[] default array[]::text[], updated_at timestamptz default now());
create table if not exists public.lego_sets (set_number text primary key, name text not null, theme text, year integer, piece_count integer, estimated_value numeric(12,2), image_url text, retired boolean default false, created_at timestamptz default now());
create table if not exists public.collection_items (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, set_number text not null references public.lego_sets(set_number), condition text not null default 'Excellent', completeness integer default 100 check(completeness between 0 and 100), original_box boolean default false, estimated_value numeric(12,2), available_for_exchange boolean default false, notes text, created_at timestamptz default now(), updated_at timestamptz default now(), unique(user_id,set_number));
create table if not exists public.wishlists (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, set_number text not null references public.lego_sets(set_number), priority integer default 3 check(priority between 1 and 5), created_at timestamptz default now(), unique(user_id,set_number));
create table if not exists public.exchange_requests (id uuid primary key default gen_random_uuid(), requester_id uuid not null references public.profiles(id), responder_id uuid not null references public.profiles(id), offered_item_id uuid not null references public.collection_items(id), requested_item_id uuid not null references public.collection_items(id), duration_days integer not null check(duration_days in(30,60,90)), offered_value numeric(12,2), requested_value numeric(12,2), proposed_deposit numeric(12,2), status text not null default 'pending' check(status in('pending','accepted','declined','cancelled','expired')), message text, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.exchanges (id uuid primary key default gen_random_uuid(), request_id uuid references public.exchange_requests(id), user_a uuid not null references public.profiles(id), user_b uuid not null references public.profiles(id), item_a uuid not null references public.collection_items(id), item_b uuid not null references public.collection_items(id), duration_days integer not null, deposit_amount numeric(12,2), payment_status text default 'not_connected', shipping_a_tracking text, shipping_b_tracking text, condition_photos_required boolean default true, state text not null default 'accepted' check(state in('accepted','deposit_pending','photos_pending','shipping','building','return_shipping','inspection','completed','disputed','cancelled')), started_at timestamptz, completed_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.reviews (id uuid primary key default gen_random_uuid(), exchange_id uuid not null references public.exchanges(id) on delete cascade, reviewer_id uuid not null references public.profiles(id), reviewee_id uuid not null references public.profiles(id), rating integer not null check(rating between 1 and 5), comment text, created_at timestamptz default now(), unique(exchange_id,reviewer_id));
create table if not exists public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, kind text, title text, body text, read_at timestamptz, created_at timestamptz default now());
create table if not exists public.messages (id uuid primary key default gen_random_uuid(), exchange_id uuid references public.exchanges(id) on delete cascade, sender_id uuid not null references public.profiles(id), recipient_id uuid not null references public.profiles(id), body text not null check(length(body) between 1 and 4000), created_at timestamptz default now(), read_at timestamptz);
create index if not exists collection_user_idx on public.collection_items(user_id); create index if not exists collection_available_idx on public.collection_items(available_for_exchange); create index if not exists wishlist_user_idx on public.wishlists(user_id); create index if not exists requests_responder_idx on public.exchange_requests(responder_id,status); create index if not exists exchanges_user_a_idx on public.exchanges(user_a,state); create index if not exists exchanges_user_b_idx on public.exchanges(user_b,state); create index if not exists notifications_user_idx on public.notifications(user_id,read_at); create index if not exists messages_exchange_idx on public.messages(exchange_id,created_at);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,display_name,email,email_verified) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''),new.email,coalesce(new.email_confirmed_at is not null,false)) on conflict(id) do nothing; insert into public.exchange_preferences(user_id) values(new.id) on conflict(user_id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security; alter table public.exchange_preferences enable row level security; alter table public.lego_sets enable row level security; alter table public.collection_items enable row level security; alter table public.wishlists enable row level security; alter table public.exchange_requests enable row level security; alter table public.exchanges enable row level security; alter table public.reviews enable row level security; alter table public.notifications enable row level security; alter table public.messages enable row level security;

drop policy if exists "catalogue readable by everyone" on public.lego_sets; create policy "catalogue readable by everyone" on public.lego_sets for select using(true);
drop policy if exists "public profiles readable" on public.profiles; create policy "public profiles readable" on public.profiles for select using(true);
drop policy if exists "users insert own profile" on public.profiles; create policy "users insert own profile" on public.profiles for insert with check(auth.uid()=id);
drop policy if exists "users update own profile" on public.profiles; create policy "users update own profile" on public.profiles for update using(auth.uid()=id) with check(auth.uid()=id);
drop policy if exists "users manage own preferences" on public.exchange_preferences; create policy "users manage own preferences" on public.exchange_preferences for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists "users read own collection" on public.collection_items; create policy "users read own collection" on public.collection_items for select using(auth.uid()=user_id or available_for_exchange=true);
drop policy if exists "users manage own collection" on public.collection_items; create policy "users manage own collection" on public.collection_items for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists "users manage own wishlist" on public.wishlists; create policy "users manage own wishlist" on public.wishlists for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists "participants read requests" on public.exchange_requests; create policy "participants read requests" on public.exchange_requests for select using(auth.uid()=requester_id or auth.uid()=responder_id);
drop policy if exists "requesters create requests" on public.exchange_requests; create policy "requesters create requests" on public.exchange_requests for insert with check(auth.uid()=requester_id);
drop policy if exists "participants update requests" on public.exchange_requests; create policy "participants update requests" on public.exchange_requests for update using(auth.uid()=requester_id or auth.uid()=responder_id) with check(auth.uid()=requester_id or auth.uid()=responder_id);
drop policy if exists "participants read exchanges" on public.exchanges; create policy "participants read exchanges" on public.exchanges for select using(auth.uid()=user_a or auth.uid()=user_b);
drop policy if exists "participants read reviews" on public.reviews; create policy "participants read reviews" on public.reviews for select using(auth.uid()=reviewer_id or auth.uid()=reviewee_id);
drop policy if exists "participants create reviews" on public.reviews; create policy "participants create reviews" on public.reviews for insert with check(auth.uid()=reviewer_id);
drop policy if exists "users read notifications" on public.notifications; create policy "users read notifications" on public.notifications for select using(auth.uid()=user_id);
drop policy if exists "users update notifications" on public.notifications; create policy "users update notifications" on public.notifications for update using(auth.uid()=user_id);
drop policy if exists "participants read messages" on public.messages; create policy "participants read messages" on public.messages for select using(auth.uid()=sender_id or auth.uid()=recipient_id);
drop policy if exists "users send messages" on public.messages; create policy "users send messages" on public.messages for insert with check(auth.uid()=sender_id);
