/* BrickCircle V3 static country/city dataset. No third-party location API is required. */
window.BC_LOCATIONS=Object.freeze({
'Afghanistan':['Kabul','Herat','Kandahar','Mazar-i-Sharif','Jalalabad'],
'Albania':['Tirana','Durrës','Vlorë','Shkodër','Elbasan'],
'Algeria':['Algiers','Oran','Constantine','Annaba','Blida'],
'Argentina':['Buenos Aires','Córdoba','Rosario','Mendoza','La Plata','Mar del Plata'],
'Armenia':['Yerevan','Gyumri','Vanadzor','Vagharshapat'],
'Australia':['Sydney','Melbourne','Brisbane','Perth','Adelaide','Canberra','Gold Coast','Hobart'],
'Austria':['Vienna','Graz','Linz','Salzburg','Innsbruck'],
'Azerbaijan':['Baku','Ganja','Sumqayit','Lankaran'],
'Bangladesh':['Dhaka','Chattogram','Khulna','Rajshahi','Sylhet','Rangpur'],
'Belarus':['Minsk','Gomel','Mogilev','Vitebsk','Grodno'],
'Belgium':['Brussels','Antwerp','Ghent','Charleroi','Liège','Bruges'],
'Bolivia':['La Paz','Santa Cruz de la Sierra','Cochabamba','Sucre','Oruro'],
'Bosnia and Herzegovina':['Sarajevo','Banja Luka','Mostar','Tuzla'],
'Brazil':['São Paulo','Rio de Janeiro','Brasília','Salvador','Belo Horizonte','Fortaleza','Curitiba','Recife','Porto Alegre'],
'Bulgaria':['Sofia','Plovdiv','Varna','Burgas','Ruse'],
'Cambodia':['Phnom Penh','Siem Reap','Battambang','Sihanoukville'],
'Canada':['Toronto','Montreal','Vancouver','Calgary','Edmonton','Ottawa','Winnipeg','Quebec City','Halifax'],
'Chile':['Santiago','Valparaíso','Concepción','Antofagasta','Viña del Mar'],
'China':['Beijing','Shanghai','Guangzhou','Shenzhen','Chengdu','Chongqing','Hangzhou','Nanjing','Wuhan','Xi’an'],
'Colombia':['Bogotá','Medellín','Cali','Barranquilla','Cartagena','Bucaramanga'],
'Costa Rica':['San José','Alajuela','Cartago','Heredia','Liberia'],
'Croatia':['Zagreb','Split','Rijeka','Osijek','Zadar'],
'Czech Republic':['Prague','Brno','Ostrava','Plzeň','Liberec'],
'Denmark':['Copenhagen','Aarhus','Odense','Aalborg','Esbjerg'],
'Dominican Republic':['Santo Domingo','Santiago de los Caballeros','La Romana','Puerto Plata'],
'Ecuador':['Quito','Guayaquil','Cuenca','Santo Domingo','Loja'],
'Egypt':['Cairo','Alexandria','Giza','Port Said','Suez','Luxor'],
'Estonia':['Tallinn','Tartu','Narva','Pärnu'],
'Ethiopia':['Addis Ababa','Dire Dawa','Mekelle','Gondar','Bahir Dar'],
'Finland':['Helsinki','Espoo','Tampere','Vantaa','Turku','Oulu'],
'France':['Paris','Marseille','Lyon','Toulouse','Nice','Nantes','Bordeaux','Lille','Strasbourg'],
'Georgia':['Tbilisi','Batumi','Kutaisi','Rustavi'],
'Germany':['Berlin','Hamburg','Munich','Cologne','Frankfurt','Stuttgart','Düsseldorf','Leipzig','Dortmund'],
'Ghana':['Accra','Kumasi','Tamale','Takoradi','Cape Coast'],
'Greece':['Athens','Thessaloniki','Patras','Heraklion','Larissa'],
'Hong Kong':['Hong Kong'],
'Hungary':['Budapest','Debrecen','Szeged','Miskolc','Pécs'],
'Iceland':['Reykjavík','Kópavogur','Hafnarfjörður','Akureyri'],
'India':['Bengaluru','Mumbai','Delhi','Hyderabad','Chennai','Kolkata','Pune','Ahmedabad','Jaipur','Kochi','Coimbatore','Mysuru','Thiruvananthapuram','Palakkad'],
'Indonesia':['Jakarta','Surabaya','Bandung','Medan','Semarang','Makassar','Denpasar','Yogyakarta'],
'Iran':['Tehran','Mashhad','Isfahan','Shiraz','Tabriz','Karaj'],
'Iraq':['Baghdad','Basra','Mosul','Erbil','Najaf','Karbala'],
'Ireland':['Dublin','Cork','Limerick','Galway','Waterford'],
'Israel':['Jerusalem','Tel Aviv','Haifa','Rishon LeZion','Petah Tikva','Beersheba'],
'Italy':['Rome','Milan','Naples','Turin','Palermo','Genoa','Bologna','Florence','Venice'],
'Jamaica':['Kingston','Montego Bay','Spanish Town','Portmore'],
'Japan':['Tokyo','Yokohama','Osaka','Nagoya','Sapporo','Fukuoka','Kobe','Kyoto','Hiroshima'],
'Jordan':['Amman','Zarqa','Irbid','Aqaba'],
'Kazakhstan':['Almaty','Astana','Shymkent','Karaganda','Aktobe'],
'Kenya':['Nairobi','Mombasa','Kisumu','Nakuru','Eldoret'],
'Kuwait':['Kuwait City','Hawally','Salmiya','Farwaniya'],
'Latvia':['Riga','Daugavpils','Liepāja','Jelgava'],
'Lebanon':['Beirut','Tripoli','Sidon','Tyre','Zahle'],
'Lithuania':['Vilnius','Kaunas','Klaipėda','Šiauliai'],
'Luxembourg':['Luxembourg City','Esch-sur-Alzette','Differdange'],
'Malaysia':['Kuala Lumpur','George Town','Johor Bahru','Ipoh','Kota Kinabalu','Kuching','Malacca City'],
'Maldives':['Malé','Addu City','Fuvahmulah'],
'Malta':['Valletta','Birkirkara','Mosta','Qormi','Sliema'],
'Mauritius':['Port Louis','Beau Bassin-Rose Hill','Vacoas-Phoenix','Curepipe'],
'Mexico':['Mexico City','Guadalajara','Monterrey','Puebla','Tijuana','Cancún','Mérida','Querétaro'],
'Moldova':['Chișinău','Tiraspol','Bălți','Bender'],
'Monaco':['Monaco'],
'Mongolia':['Ulaanbaatar','Erdenet','Darkhan'],
'Morocco':['Casablanca','Rabat','Marrakesh','Fes','Tangier','Agadir','Meknes'],
'Nepal':['Kathmandu','Pokhara','Lalitpur','Bharatpur','Biratnagar'],
'Netherlands':['Amsterdam','Rotterdam','The Hague','Utrecht','Eindhoven','Groningen'],
'New Zealand':['Auckland','Wellington','Christchurch','Hamilton','Tauranga','Dunedin'],
'Nigeria':['Lagos','Abuja','Kano','Ibadan','Port Harcourt','Benin City','Enugu'],
'North Macedonia':['Skopje','Bitola','Kumanovo','Ohrid'],
'Norway':['Oslo','Bergen','Trondheim','Stavanger','Drammen'],
'Oman':['Muscat','Salalah','Sohar','Nizwa','Sur'],
'Pakistan':['Karachi','Lahore','Islamabad','Rawalpindi','Faisalabad','Peshawar','Quetta'],
'Panama':['Panama City','San Miguelito','Colón','David'],
'Peru':['Lima','Arequipa','Trujillo','Cusco','Chiclayo','Piura'],
'Philippines':['Manila','Quezon City','Cebu City','Davao City','Zamboanga','Taguig'],
'Poland':['Warsaw','Kraków','Łódź','Wrocław','Poznań','Gdańsk','Szczecin'],
'Portugal':['Lisbon','Porto','Braga','Coimbra','Funchal','Aveiro'],
'Qatar':['Doha','Al Rayyan','Al Wakrah','Umm Salal'],
'Romania':['Bucharest','Cluj-Napoca','Timișoara','Iași','Constanța','Brașov'],
'Russia':['Moscow','Saint Petersburg','Novosibirsk','Yekaterinburg','Kazan','Nizhny Novgorod','Samara'],
'Saudi Arabia':['Riyadh','Jeddah','Mecca','Medina','Dammam','Khobar','Abha'],
'Serbia':['Belgrade','Novi Sad','Niš','Kragujevac','Subotica'],
'Singapore':['Singapore'],
'Slovakia':['Bratislava','Košice','Prešov','Žilina','Nitra'],
'Slovenia':['Ljubljana','Maribor','Celje','Kranj'],
'South Africa':['Johannesburg','Cape Town','Durban','Pretoria','Gqeberha','Bloemfontein'],
'South Korea':['Seoul','Busan','Incheon','Daegu','Daejeon','Gwangju','Suwon'],
'Spain':['Madrid','Barcelona','Valencia','Seville','Zaragoza','Málaga','Bilbao','Alicante'],
'Sri Lanka':['Colombo','Kandy','Galle','Jaffna','Negombo','Sri Jayawardenepura Kotte'],
'Sweden':['Stockholm','Gothenburg','Malmö','Uppsala','Västerås'],
'Switzerland':['Zurich','Geneva','Basel','Bern','Lausanne','Lucerne'],
'Taiwan':['Taipei','New Taipei City','Taichung','Kaohsiung','Tainan','Hsinchu'],
'Tanzania':['Dar es Salaam','Dodoma','Arusha','Mwanza','Zanzibar City'],
'Thailand':['Bangkok','Chiang Mai','Pattaya','Phuket','Hat Yai','Khon Kaen'],
'Tunisia':['Tunis','Sfax','Sousse','Kairouan','Bizerte'],
'Turkey':['Istanbul','Ankara','Izmir','Bursa','Antalya','Adana','Gaziantep'],
'Uganda':['Kampala','Entebbe','Jinja','Mbarara','Gulu'],
'Ukraine':['Kyiv','Kharkiv','Odesa','Dnipro','Lviv','Vinnytsia'],
'United Arab Emirates':['Dubai','Abu Dhabi','Sharjah','Ajman','Al Ain','Ras Al Khaimah'],
'United Kingdom':['London','Birmingham','Manchester','Glasgow','Liverpool','Edinburgh','Leeds','Bristol','Cardiff','Belfast'],
'United States':['New York','Los Angeles','Chicago','Houston','Phoenix','Philadelphia','San Antonio','San Diego','Dallas','San Francisco','Seattle','Boston','Washington, D.C.','Miami','Atlanta','Denver','Austin','Las Vegas'],
'Uruguay':['Montevideo','Salto','Ciudad de la Costa','Paysandú'],
'Uzbekistan':['Tashkent','Samarkand','Namangan','Andijan','Bukhara'],
'Venezuela':['Caracas','Maracaibo','Valencia','Barquisimeto','Maracay'],
'Vietnam':['Ho Chi Minh City','Hanoi','Da Nang','Hai Phong','Can Tho','Nha Trang'],
'Zambia':['Lusaka','Kitwe','Ndola','Livingstone'],
'Zimbabwe':['Harare','Bulawayo','Chitungwiza','Mutare']
});
