/* BrickCircle V2.2 Exchange Engine. Runs alongside the stable V2.1 client. */
(()=>{
const SB_URL='https://nsxtromjdpdscknadxez.supabase.co',SB_KEY='sb_publishable_JJhVbgjGblHrnKuPOsJkxQ_zRoQNlIL';
const db22=window.supabase.createClient(SB_URL,SB_KEY);const app22=()=>document.querySelector('#app');const modal22=()=>document.querySelector('#modal');
let originalNav=window.bcNav;let state={user:null,requests:[],exchanges:[],notifications:[],messages:[],profiles:{},items:{},sets:{}};
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=x=>'$'+Number(x||0).toLocaleString();
const label=s=>String(s||'').replace(/_/g,' ').replace(/\b\w/g,m=>m.toUpperCase());
const badge=s=>`<span class="pill ${['accepted','completed','ok'].includes(s)?'ok':(['declined','cancelled','disputed'].includes(s)?'bad':'warn')}">${esc(label(s))}</span>`;
const css=document.createElement('style');css.textContent=`.v22nav{display:flex;gap:7px;flex-wrap:wrap;margin:0 0 20px}.v22nav button{border:1px solid #d9dee7;background:#fff;border-radius:9px;padding:9px 12px;font-weight:750;cursor:pointer}.v22nav .on{background:#111827;color:#fff;border-color:#111827}.v22grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.v22card{background:#fff;border:1px solid #e5e7eb;border-radius:15px;padding:18px}.v22card h3{margin:8px 0}.v22muted{color:#667085}.v22actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.v22actions button{border:1px solid #d9dee7;background:#fff;border-radius:9px;padding:9px 12px;font-weight:750;cursor:pointer}.v22actions .primary{background:#111827;color:#fff;border-color:#111827}.v22actions .danger{background:#fff1f2;color:#b42318;border-color:#fecdd3}.v22timeline{display:grid;gap:8px;margin-top:12px}.v22step{display:flex;align-items:center;gap:10px;padding:10px 12px;border:1px solid #e5e7eb;border-radius:10px}.v22dot{width:12px;height:12px;border-radius:50%;background:#d0d5dd}.v22step.active .v22dot{background:#111827}.v22step.done .v22dot{background:#12b76a}.v22notice{padding:12px 14px;background:#f8fafc;border:1px solid #e5e7eb;border-radius:10px;margin:10px 0}.v22tabs{display:flex;gap:7px;margin:14px 0}.v22tabs button{border:1px solid #d9dee7;background:#fff;border-radius:9px;padding:9px 12px;font-weight:750}.v22tabs .on{background:#111827;color:#fff}.v22unread{display:inline-flex;min-width:20px;height:20px;padding:0 6px;border-radius:999px;background:#d92d20;color:#fff;align-items:center;justify-content:center;font-size:11px}.v22form{display:grid;gap:10px}.v22form input,.v22form select,.v22form textarea{padding:11px;border:1px solid #d9dee7;border-radius:9px;background:#fff;font:inherit;width:100%}.v22chat{max-height:330px;overflow:auto;display:grid;gap:8px}.v22msg{padding:10px 12px;border-radius:12px;background:#f2f4f7;max-width:80%}.v22msg.mine{margin-left:auto;background:#e8f3ff}.bad{background:#fff1f2!important;color:#b42318}.warn{background:#fff3d6!important;color:#9a6700}.ok{background:#ecfdf3!important;color:#027a48}@media(max-width:800px){.v22grid{grid-template-columns:1fr}}`;document.head.appendChild(css);
function current(){return location.hash.replace('#','')||'home'}
function nav(){const p=current();const unread=state.notifications.filter(n=>!n.read_at).length;return `<div class="v22nav">${[['home','Home'],['catalogue','Catalogue'],['collection','My collection'],['wishlist','Wishlist'],['matches','Matches'],['requests','Requests'],['exchanges','My Exchanges'],['messages','Messages'],['notifications',`Notifications ${unread?`<span class="v22unread">${unread}</span>`:''}`],['profile','Profile']].map(([k,t])=>`<button class="${p===k?'on':''}" onclick="bc22Nav('${k}')">${t}</button>`).join('')}</div>`}
function shell(body){const root=app22();if(!root)return;root.innerHTML=`<div class="wrap">${nav()}${body}<div class="footer">BrickCircle V2.2 · Exchange Engine · Supabase RLS protected</div></div>`}
async function refresh(){const {data:{user}}=await db22.auth.getUser();state.user=user||null;if(!user){state.requests=[];state.exchanges=[];state.notifications=[];state.messages=[];return}const [r,e,n,m]=await Promise.all([db22.from('exchange_requests').select('*').or(`requester_id.eq.${user.id},responder_id.eq.${user.id}`).order('created_at',{ascending:false}),db22.from('exchanges').select('*').or(`user_a.eq.${user.id},user_b.eq.${user.id}`).order('created_at',{ascending:false}),db22.from('notifications').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).limit(50),db22.from('messages').select('*').or(`sender_id.eq.${user.id},recipient_id.eq.${user.id}`).order('created_at',{ascending:false}).limit(100)]);state.requests=r.data||[];state.exchanges=e.data||[];state.notifications=n.data||[];state.messages=m.data||[];await hydrate()}
async function hydrate(){const ids=new Set();state.requests.forEach(r=>{ids.add(r.requester_id);ids.add(r.responder_id);ids.add(r.offered_item_id);ids.add(r.requested_item_id)});state.exchanges.forEach(e=>{ids.add(e.user_a);ids.add(e.user_b);ids.add(e.item_a);ids.add(e.item_b)});const itemIds=[...ids].filter(x=>state.requests.some(r=>r.offered_item_id===x||r.requested_item_id===x)||state.exchanges.some(e=>e.item_a===x||e.item_b===x));const userIds=[...ids].filter(x=>state.requests.some(r=>r.requester_id===x||r.responder_id===x)||state.exchanges.some(e=>e.user_a===x||e.user_b===x));if(itemIds.length){const {data}=await db22.from('collection_items').select('*').in('id',itemIds);(data||[]).forEach(x=>state.items[x.id]=x);const sns=[...(data||[]).map(x=>x.set_number)];if(sns.length){const {data:sets}=await db22.from('lego_sets').select('*').in('set_number',sns);(sets||[]).forEach(x=>state.sets[x.set_number]=x)}}if(userIds.length){const {data}=await db22.from('profiles').select('id,display_name,country,city,rating,trust_score').in('id',userIds);(data||[]).forEach(x=>state.profiles[x.id]=x)}}
function person(id){return state.profiles[id]?.display_name||'Collector'}
function item(id){const i=state.items[id];return i?state.sets[i.set_number]||{name:i.set_number,set_number:i.set_number}:null}
function itemName(id){const s=item(id);return s?.name||state.items[id]?.set_number||'LEGO set'}
function setNum(id){const i=state.items[id];return i?.set_number||''}
function auth(){if(!state.user){window.bcAuth();return false}return true}
function requestCard(r,incoming){const offer=itemName(r.offered_item_id),want=itemName(r.requested_item_id),other=incoming?r.requester_id:r.responder_id;return `<div class="v22card"><div>${badge(r.status)} <span class="v22muted">${new Date(r.created_at).toLocaleString()}</span></div><h3>${esc(incoming?person(r.requester_id):person(r.responder_id))}</h3><p><b>${esc(offer)}</b> <span class="v22muted">for</span> <b>${esc(want)}</b></p><p class="v22muted">${r.duration_days} days · Proposed deposit ${money(r.proposed_deposit)}</p>${r.message?`<div class="v22notice">${esc(r.message)}</div>`:''}<div class="v22actions">${r.status==='pending'&&incoming?`<button class="primary" onclick="bc22Respond('${r.id}','accept')">Accept</button><button class="danger" onclick="bc22Respond('${r.id}','decline')">Decline</button><button onclick="bc22OpenChat('${other}')">Message</button>`:''}${r.status==='pending'&&!incoming?`<button class="danger" onclick="bc22Respond('${r.id}','cancel')">Cancel request</button><button onclick="bc22OpenChat('${other}')">Message</button>`:''}${r.status==='accepted'?`<button class="primary" onclick="bc22Nav('exchanges')">Open exchange</button>`:''}</div></div>`}
function requests(){if(!auth())return;shell(`<div class="v22card"><h2>Exchange Request Centre</h2><p class="v22muted">Every request is tied to two specific collection items. Accepting a request creates a live exchange and starts its workflow.</p></div><div class="v22tabs"><button id="rin" class="on" onclick="bc22ReqTab('in')">Incoming</button><button id="rout" onclick="bc22ReqTab('out')">Outgoing</button></div><div id="reqbody"></div>`);bc22ReqTab('in')}
window.bc22ReqTab=function(t){document.querySelector('#rin')?.classList.toggle('on',t==='in');document.querySelector('#rout')?.classList.toggle('on',t==='out');const inc=t==='in';const rows=state.requests.filter(r=>inc?r.responder_id===state.user.id:r.requester_id===state.user.id);const x=document.querySelector('#reqbody');if(x)x.innerHTML=rows.map(r=>requestCard(r,inc)).join('')||`<div class="v22notice">No ${inc?'incoming':'outgoing'} requests.</div>`}
async function respond(id,action){const {error}=await db22.rpc('respond_exchange_request',{p_request_id:id,p_action:action});if(error)return alert(error.message);await refresh();bc22Render()}
function exchanges(){if(!auth())return;const rows=state.exchanges;shell(`<div class="v22card"><h2>My Exchanges</h2><p class="v22muted">Track accepted swaps from deposit through return and completion.</p><div class="v22actions"><span class="pill ok">${rows.filter(x=>!['completed','cancelled'].includes(x.state)).length} active</span><span class="pill">${rows.filter(x=>x.state==='completed').length} completed</span></div></div><div style="height:14px"></div><div class="v22grid">${rows.map(exchangeCard).join('')||'<div class="v22notice">No exchanges yet. Find a reciprocal match and send a request.</div>'}</div>`)}
const flow=['accepted','deposit_pending','photos_pending','shipping','building','return_shipping','inspection','completed'];
function exchangeCard(e){const mine=e.user_a===state.user.id,other=mine?e.user_b:e.user_a;const a=mine?e.item_a:e.item_b,b=mine?e.item_b:e.item_a;const idx=flow.indexOf(e.state);return `<div class="v22card"><div>${badge(e.state)} <span class="v22muted">${new Date(e.created_at).toLocaleDateString()}</span></div><h3>${esc(itemName(a))} ↔ ${esc(itemName(b))}</h3><p class="v22muted">With ${esc(person(other))} · ${e.duration_days} days · Deposit ${money(e.deposit_amount)}</p><div class="v22timeline">${flow.map((s,i)=>`<div class="v22step ${i<idx?'done':''} ${i===idx?'active':''}"><span class="v22dot"></span><span>${label(s)}</span></div>`).join('')}</div>${e.shipping_a_tracking||e.shipping_b_tracking?`<div class="v22notice">Tracking: ${esc(e.shipping_a_tracking||e.shipping_b_tracking)}</div>`:''}<div class="v22actions">${nextActions(e)}<button onclick="bc22OpenExchangeChat('${e.id}','${other}')">Messages</button></div></div>`}
function nextActions(e){if(e.state==='completed'||e.state==='cancelled')return '';const n={accepted:'deposit_pending',deposit_pending:'photos_pending',photos_pending:'shipping',shipping:'building',building:'return_shipping',return_shipping:'inspection',inspection:'completed'}[e.state];if(!n)return `<button class="danger" onclick="bc22Advance('${e.id}','cancelled')">Cancel</button>`;return `<button class="primary" onclick="bc22Advance('${e.id}','${n}')">Mark ${label(n)}</button>${e.state==='shipping'||e.state==='return_shipping'?`<button onclick="bc22Tracking('${e.id}','${n}')">Add tracking</button>`:''}`}
async function advance(id,next,tracking=null){const {error}=await db22.rpc('advance_exchange',{p_exchange_id:id,p_state:next,p_tracking:tracking});if(error)return alert(error.message);await refresh();bc22Render()}
function tracking(id,next){const t=prompt('Enter tracked shipping number');if(t)advance(id,next,t)}
function notifications(){if(!auth())return;shell(`<div class="v22card"><div style="display:flex;justify-content:space-between;gap:10px;align-items:center"><div><h2>Notifications</h2><p class="v22muted">Exchange events and account activity.</p></div><button onclick="bc22ReadAll()">Mark all read</button></div></div><div style="height:14px"></div>${state.notifications.map(n=>`<div class="v22notice" style="opacity:${n.read_at?.9||1}"><div>${n.read_at?'':'🔔 '}<b>${esc(n.title||label(n.kind))}</b></div><div>${esc(n.body||'')}</div><small class="v22muted">${new Date(n.created_at).toLocaleString()}</small>${!n.read_at?`<div class="v22actions"><button onclick="bc22Read('${n.id}')">Mark read</button></div>`:''}</div>`).join('')||'<div class="v22notice">No notifications yet.</div>'}`)}
async function read(id){const {error}=await db22.from('notifications').update({read_at:new Date().toISOString()}).eq('id',id).eq('user_id',state.user.id);if(error)alert(error.message);else{await refresh();bc22Render()}}
async function readAll(){const {error}=await db22.from('notifications').update({read_at:new Date().toISOString()}).eq('user_id',state.user.id).is('read_at',null);if(error)alert(error.message);else{await refresh();bc22Render()}}
function messages(){if(!auth())return;const rows=state.messages;const grouped={};rows.forEach(m=>{const k=m.exchange_id||['dm',...([m.sender_id,m.recipient_id].sort())].join(':');(grouped[k]??=[]).push(m)});shell(`<div class="v22card"><h2>Messages</h2><p class="v22muted">Conversations are grouped by exchange when an exchange exists.</p></div><div style="height:14px"></div>${Object.entries(grouped).map(([k,ms])=>{const first=ms[0],other=first.sender_id===state.user.id?first.recipient_id:first.sender_id;return `<div class="v22card" style="margin-bottom:12px"><h3>${esc(first.exchange_id?'Exchange conversation':'Collector conversation')} · ${esc(person(other))}</h3><div class="v22chat">${ms.slice().reverse().map(m=>`<div class="v22msg ${m.sender_id===state.user.id?'mine':''}">${esc(m.body)}<br><small class="v22muted">${new Date(m.created_at).toLocaleString()}</small></div>`).join('')}</div><div class="v22actions"><button class="primary" onclick="bc22OpenChat('${other}','${first.exchange_id||''}')">Reply</button></div></div>`}).join('')||'<div class="v22notice">No messages yet.</div>'}`)}
function openChat(other,exchange=''){modal22().innerHTML=`<div class="modalback"><div class="modalbox"><button class="close" onclick="bcClose()">×</button><h2>Message ${esc(person(other))}</h2><form class="v22form" onsubmit="bc22Send(event,'${other}','${exchange}')"><textarea id="v22body" maxlength="4000" rows="6" required placeholder="Write your message"></textarea><button class="primary">Send message</button></form></div></div>`}
async function send(e,other,exchange){e.preventDefault();const {error}=await db22.from('messages').insert({exchange_id:exchange||null,sender_id:state.user.id,recipient_id:other,body:document.querySelector('#v22body').value});if(error)alert(error.message);else{bcClose();await refresh();bc22Render()}}
function profile(){if(originalNav)originalNav('profile')}
function render(){const p=current();if(['requests','exchanges','notifications','messages'].includes(p)){({requests,exchanges,notifications,messages}[p])();}else if(originalNav)originalNav(p)}
window.bc22Nav=p=>{location.hash=p;render()};window.bc22Respond=respond;window.bc22Advance=advance;window.bc22Tracking=tracking;window.bc22Read=read;window.bc22ReadAll=readAll;window.bc22OpenChat=openChat;window.bc22OpenExchangeChat=(id,other)=>openChat(other,id);window.bc22Send=send;
async function bc22Render(){await refresh();render()}
window.bcNav=window.bc22Nav;
db22.auth.onAuthStateChange(()=>setTimeout(()=>bc22Render(),50));
setTimeout(()=>bc22Render(),100);
})();