(()=>{
const U='https://nsxtromjdpdscknadxez.supabase.co',K='sb_publishable_JJhVbgjGblHrnKuPOsJkxQ_zRoQNlIL',db=window.supabase.createClient(U,K),root=()=>document.querySelector('#app'),modal=()=>document.querySelector('#modal');
const oldNav=window.bcNav;let S={u:null,r:[],e:[],n:[],m:[],p:{},i:{},s:{}};
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=x=>'$'+Number(x||0).toLocaleString(),lab=x=>String(x||'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase()),pg=()=>location.hash.slice(1)||'home';
const tag=x=>`<span class="pill ${['accepted','completed'].includes(x)?'ok':['declined','cancelled','disputed'].includes(x)?'bad':'warn'}">${esc(lab(x))}</span>`;
const st=document.createElement('style');st.textContent=`.xnav{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:20px}.xnav button,.xact button,.xtabs button{border:1px solid #d9dee7;background:#fff;border-radius:9px;padding:9px 12px;font-weight:750;cursor:pointer}.xnav .on,.xact .primary,.xtabs .on{background:#111827;color:#fff;border-color:#111827}.xgrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.xcard{background:#fff;border:1px solid #e5e7eb;border-radius:15px;padding:18px}.xmuted{color:#667085}.xact{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.xact .danger{background:#fff1f2;color:#b42318;border-color:#fecdd3}.xtabs{display:flex;gap:7px;margin:14px 0}.xtime{display:grid;gap:7px;margin:12px 0}.xstep{display:flex;gap:10px;align-items:center;padding:9px 11px;border:1px solid #e5e7eb;border-radius:9px}.xdot{width:12px;height:12px;border-radius:50%;background:#d0d5dd}.xstep.active .xdot{background:#111827}.xstep.done .xdot{background:#12b76a}.xnotice{padding:12px 14px;background:#f8fafc;border:1px solid #e5e7eb;border-radius:10px;margin:9px 0}.xchat{max-height:330px;overflow:auto;display:grid;gap:8px}.xmsg{padding:10px 12px;border-radius:12px;background:#f2f4f7;max-width:80%}.xmsg.mine{margin-left:auto;background:#e8f3ff}.xform{display:grid;gap:10px}.xform textarea{padding:11px;border:1px solid #d9dee7;border-radius:9px;font:inherit;width:100%}.bad{background:#fff1f2!important;color:#b42318}.warn{background:#fff3d6!important;color:#9a6700}.ok{background:#ecfdf3!important;color:#027a48}@media(max-width:800px){.xgrid{grid-template-columns:1fr}}`;document.head.appendChild(st);
function nav(){let p=pg(),un=S.n.filter(x=>!x.read_at).length;return `<div class="xnav">${[['home','Home'],['catalogue','Catalogue'],['collection','My collection'],['wishlist','Wishlist'],['matches','Matches'],['requests','Requests'],['exchanges','My Exchanges'],['messages','Messages'],['notifications','Notifications'+(un?' ('+un+')':'')],['profile','Profile']].map(a=>`<button class="${p===a[0]?'on':''}" onclick="bc22Nav('${a[0]}')">${a[1]}</button>`).join('')}</div>`}
function shell(b){root().innerHTML=`<div class="wrap">${nav()}${b}<div class="footer">BrickCircle V2.2 · Exchange Engine · Supabase RLS protected</div></div>`}
async function load(){const {data:{user}}=await db.auth.getUser();S.u=user||null;if(!user){S.r=[];S.e=[];S.n=[];S.m=[];return}const q=await Promise.all([db.from('exchange_requests').select('*').or(`requester_id.eq.${user.id},responder_id.eq.${user.id}`).order('created_at',{ascending:false}),db.from('exchanges').select('*').or(`user_a.eq.${user.id},user_b.eq.${user.id}`).order('created_at',{ascending:false}),db.from('notifications').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).limit(50),db.from('messages').select('*').or(`sender_id.eq.${user.id},recipient_id.eq.${user.id}`).order('created_at',{ascending:false}).limit(100)]);S.r=q[0].data||[];S.e=q[1].data||[];S.n=q[2].data||[];S.m=q[3].data||[];await hydrate()}
async function hydrate(){const us=new Set(),is=new Set();S.r.forEach(x=>{us.add(x.requester_id);us.add(x.responder_id);is.add(x.offered_item_id);is.add(x.requested_item_id)});S.e.forEach(x=>{us.add(x.user_a);us.add(x.user_b);is.add(x.item_a);is.add(x.item_b)});const [ip,up]=await Promise.all([is.size?db.from('collection_items').select('*').in('id',[...is]):Promise.resolve({data:[]}),us.size?db.from('profiles').select('id,display_name').in('id',[...us]):Promise.resolve({data:[]})]);(ip.data||[]).forEach(x=>S.i[x.id]=x);(up.data||[]).forEach(x=>S.p[x.id]=x.display_name||'Collector');const sn=[...(ip.data||[])].map(x=>x.set_number);if(sn.length){const {data}=await db.from('lego_sets').select('*').in('set_number',sn);(data||[]).forEach(x=>S.s[x.set_number]=x)}}
const person=id=>S.p[id]||'Collector',iname=id=>S.s[S.i[id]?.set_number]?.name||S.i[id]?.set_number||'LEGO set';
function need(){if(!S.u){window.bcAuth();return false}return true}
function requests(){if(!need())return;shell(`<div class="xcard"><h2>Exchange Request Centre</h2><p class="xmuted">Manage incoming and outgoing proposals. Accepting a request creates the live exchange automatically.</p></div><div class="xtabs"><button id="xin" class="on" onclick="bc22Req('in')">Incoming</button><button id="xout" onclick="bc22Req('out')">Outgoing</button></div><div id="xreq"></div>`);bc22Req('in')}
window.bc22Req=t=>{document.querySelector('#xin')?.classList.toggle('on',t==='in');document.querySelector('#xout')?.classList.toggle('on',t==='out');let inc=t==='in',rows=S.r.filter(x=>inc?x.responder_id===S.u.id:x.requester_id===S.u.id);document.querySelector('#xreq').innerHTML=rows.map(r=>`<div class="xcard" style="margin-bottom:12px"><div>${tag(r.status)} <span class="xmuted">${new Date(r.created_at).toLocaleString()}</span></div><h3>${esc(person(inc?r.requester_id:r.responder_id))}</h3><p><b>${esc(iname(r.offered_item_id))}</b> <span class="xmuted">for</span> <b>${esc(iname(r.requested_item_id))}</b></p><p class="xmuted">${r.duration_days} days · Proposed deposit ${money(r.proposed_deposit)}</p>${r.message?`<div class="xnotice">${esc(r.message)}</div>`:''}<div class="xact">${r.status==='pending'&&inc?`<button class="primary" onclick="bc22Respond('${r.id}','accept')">Accept</button><button class="danger" onclick="bc22Respond('${r.id}','decline')">Decline</button>`:''}${r.status==='pending'&&!inc?`<button class="danger" onclick="bc22Respond('${r.id}','cancel')">Cancel</button>`:''}${r.status==='accepted'?`<button class="primary" onclick="bc22Nav('exchanges')">Open exchange</button>`:''}<button onclick="bc22Chat('${inc?r.requester_id:r.responder_id}','')">Message</button></div></div>`).join('')||`<div class="xnotice">No ${inc?'incoming':'outgoing'} requests.</div>`}
window.bc22Respond=async(id,a)=>{const {error}=await db.rpc('respond_exchange_request',{p_request_id:id,p_action:a});if(error)alert(error.message);else{await load();render()}};
const flow=['accepted','deposit_pending','photos_pending','shipping','building','return_shipping','inspection','completed'];
function exchanges(){if(!need())return;shell(`<div class="xcard"><h2>My Exchanges</h2><p class="xmuted">Your accepted swaps now have a complete lifecycle: deposit → photos → shipping → building → return → inspection → completion.</p><div class="xact"><span class="pill ok">${S.e.filter(x=>!['completed','cancelled'].includes(x.state)).length} active</span><span class="pill">${S.e.filter(x=>x.state==='completed').length} completed</span></div></div><div style="height:14px"></div><div class="xgrid">${S.e.map(exCard).join('')||'<div class="xnotice">No exchanges yet.</div>'}</div>`)}
function exCard(e){let mine=e.user_a===S.u.id,other=mine?e.user_b:e.user_a,a=mine?e.item_a:e.item_b,b=mine?e.item_b:e.item_a,idx=flow.indexOf(e.state);let next={accepted:'deposit_pending',deposit_pending:'photos_pending',photos_pending:'shipping',shipping:'building',building:'return_shipping',return_shipping:'inspection',inspection:'completed'}[e.state];return `<div class="xcard"><div>${tag(e.state)} <span class="xmuted">${new Date(e.created_at).toLocaleDateString()}</span></div><h3>${esc(iname(a))} ↔ ${esc(iname(b))}</h3><p class="xmuted">With ${esc(person(other))} · ${e.duration_days} days · Deposit ${money(e.deposit_amount)}</p><div class="xtime">${flow.map((s,i)=>`<div class="xstep ${i<idx?'done':''} ${i===idx?'active':''}"><span class="xdot"></span>${lab(s)}</div>`).join('')}</div>${e.shipping_a_tracking||e.shipping_b_tracking?`<div class="xnotice">Tracking: ${esc(e.shipping_a_tracking||e.shipping_b_tracking)}</div>`:''}<div class="xact">${next?`<button class="primary" onclick="bc22Advance('${e.id}','${next}')">Mark ${lab(next)}</button>`:''}${e.state==='shipping'||e.state==='return_shipping'?`<button onclick="bc22Track('${e.id}','${next}')">Add tracking</button>`:''}${!['completed','cancelled'].includes(e.state)?`<button class="danger" onclick="bc22Advance('${e.id}','cancelled')">Cancel</button>`:''}<button onclick="bc22Chat('${other}','${e.id}')">Messages</button></div></div>`}
window.bc22Advance=async(id,state,tracking=null)=>{const {error}=await db.rpc('advance_exchange',{p_exchange_id:id,p_state:state,p_tracking:tracking});if(error)alert(error.message);else{await load();render()}};
window.bc22Track=(id,next)=>{let t=prompt('Enter tracked shipping number');if(t)bc22Advance(id,next,t)};
function notifications(){if(!need())return;shell(`<div class="xcard"><h2>Notifications</h2><p class="xmuted">Exchange events and account activity.</p><button onclick="bc22ReadAll()">Mark all read</button></div><div style="height:14px"></div>${S.n.map(n=>`<div class="xnotice"><b>${n.read_at?'':'🔔 '}${esc(n.title||lab(n.kind))}</b><div>${esc(n.body||'')}</div><small class="xmuted">${new Date(n.created_at).toLocaleString()}</small>${!n.read_at?`<div class="xact"><button onclick="bc22Read('${n.id}')">Mark read</button></div>`:''}</div>`).join('')||'<div class="xnotice">No notifications yet.</div>'}`)}
window.bc22Read=async id=>{const {error}=await db.from('notifications').update({read_at:new Date().toISOString()}).eq('id',id).eq('user_id',S.u.id);if(error)alert(error.message);else{await load();render()}};window.bc22ReadAll=async()=>{const {error}=await db.from('notifications').update({read_at:new Date().toISOString()}).eq('user_id',S.u.id).is('read_at',null);if(error)alert(error.message);else{await load();render()}};
function messages(){if(!need())return;let groups={};S.m.forEach(m=>{let k=m.exchange_id||[m.sender_id,m.recipient_id].sort().join(':');(groups[k]??=[]).push(m)});shell(`<div class="xcard"><h2>Messages</h2><p class="xmuted">Conversations are grouped by exchange.</p></div><div style="height:14px"></div>${Object.values(groups).map(ms=>{let f=ms[0],other=f.sender_id===S.u.id?f.recipient_id:f.sender_id;return `<div class="xcard" style="margin-bottom:12px"><h3>${f.exchange_id?'Exchange':'Collector'} · ${esc(person(other))}</h3><div class="xchat">${ms.slice().reverse().map(m=>`<div class="xmsg ${m.sender_id===S.u.id?'mine':''}">${esc(m.body)}<br><small class="xmuted">${new Date(m.created_at).toLocaleString()}</small></div>`).join('')}</div><div class="xact"><button class="primary" onclick="bc22Chat('${other}','${f.exchange_id||''}')">Reply</button></div></div>`}).join('')||'<div class="xnotice">No messages yet.</div>'}`)}
window.bc22Chat=(other,exchange)=>{modal().innerHTML=`<div class="modalback"><div class="modalbox"><button class="close" onclick="bcClose()">×</button><h2>Message ${esc(person(other))}</h2><form class="xform" onsubmit="bc22Send(event,'${other}','${exchange||''}')"><textarea id="xbody" rows="6" maxlength="4000" required placeholder="Write your message"></textarea><button class="primary">Send message</button></form></div></div>`};window.bc22Send=async(e,other,exchange)=>{e.preventDefault();const {error}=await db.from('messages').insert({exchange_id:exchange||null,sender_id:S.u.id,recipient_id:other,body:document.querySelector('#xbody').value});if(error)alert(error.message);else{bcClose();await load();render()}};
function render(){let p=pg();if(['requests','exchanges','notifications','messages'].includes(p))({requests,exchanges,notifications,messages}[p])();else if(oldNav)oldNav(p)}
window.bc22Nav=p=>{location.hash=p;render()};window.bcNav=window.bc22Nav;db.auth.onAuthStateChange(()=>setTimeout(async()=>{await load();render()},100));setTimeout(async()=>{await load();render()},200);
})();