/* BrickCircle V2.2 matching hotfix: use the server-side reciprocal matcher so RLS cannot hide other collectors. */
(()=>{
const URL='https://nsxtromjdpdscknadxez.supabase.co',KEY='sb_publishable_JJhVbgjGblHrnKuPOsJkxQ_zRoQNlIL',db=window.supabase.createClient(URL,KEY),app=()=>document.querySelector('#app'),esc=x=>String(x??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c])),money=x=>'$'+Number(x||0).toLocaleString();
const css=document.createElement('style');css.textContent='.mcard{background:#fff;border:1px solid #e5e7eb;border-radius:15px;padding:18px;margin-bottom:14px}.mhero{padding:18px;background:#f8fafc;border:1px solid #e5e7eb;border-radius:14px;margin-bottom:14px}.mact{display:flex;gap:8px;flex-wrap:wrap;margin-top:13px}.mact button{border:1px solid #d9dee7;background:#fff;border-radius:9px;padding:9px 12px;font-weight:750;cursor:pointer}.mact .primary{background:#111827;color:#fff;border-color:#111827}.merr{background:#fff1f2;border:1px solid #fecdd3;color:#b42318;padding:12px;border-radius:10px}';document.head.appendChild(css);
async function matchesPage(){const {data:{user}}=await db.auth.getUser();if(!user){if(window.bcAuth)window.bcAuth();return}const root=app();root.innerHTML='<div class="wrap"><div class="tabs"><button class="on">Matches</button></div><div class="mcard"><h2>Smart matches</h2><p>BrickCircle is checking your collection and wishlist against every available collector.</p></div><div id="matchlist">Checking for reciprocal matches…</div></div>';
const {data,error}=await db.rpc('find_matches',{p_user:user.id});
if(error){document.querySelector('#matchlist').innerHTML=`<div class="merr"><b>Unable to load matches.</b><br>${esc(error.message)}</div>`;return}
const rows=(data||[]).map(r=>({other:r.match_user,offered:{id:r.offered_item,set_number:r.offered_set,name:r.offered_name,estimated_value:r.offered_value},requested:{id:r.requested_item,set_number:r.requested_set,name:r.requested_name,estimated_value:r.requested_value},score:r.match_score}));
if(!rows.length){document.querySelector('#matchlist').innerHTML='<div class="mhero"><b>No reciprocal matches yet.</b><br>Both users must have an available set and a reciprocal wishlist entry.</div>';window.__bcMatches=[];return}
const ids=[...new Set(rows.map(r=>r.other))];const {data:profiles,error:pe}=await db.from('profiles').select('id,display_name').in('id',ids);if(pe){document.querySelector('#matchlist').innerHTML=`<div class="merr">Unable to load collector profiles: ${esc(pe.message)}</div>`;return}const pn=new Map((profiles||[]).map(p=>[p.id,p.display_name||'Collector']));
document.querySelector('#matchlist').innerHTML=rows.map((r,i)=>`<div class="mcard"><div><b>${esc(pn.get(r.other)||'Collector')}</b> is a reciprocal match</div><h3>You offer ${esc(r.offered.name||r.offered.set_number)} for ${esc(r.requested.name||r.requested.set_number)}</h3><p>Set ${esc(r.offered.set_number)} ↔ Set ${esc(r.requested.set_number)} · ${money(r.offered.estimated_value)} ↔ ${money(r.requested.estimated_value)}</p><div class="mact"><button class="primary" onclick="bc22Propose(${i})">Propose exchange</button><button onclick="bc22Msg('${r.other}')">Message collector</button></div></div>`).join('');window.__bcMatches=rows;}
window.bc22Propose=async i=>{const r=window.__bcMatches?.[i];if(!r)return;const days=Number(prompt('Exchange duration in days (30, 60 or 90)','30'));if(![30,60,90].includes(days)){alert('Please choose 30, 60 or 90 days.');return}const msg=prompt('Optional message to the collector:','I would like to exchange these sets.');const {data:{user}}=await db.auth.getUser();const {error}=await db.from('exchange_requests').insert({requester_id:user.id,responder_id:r.other,offered_item_id:r.offered.id,requested_item_id:r.requested.id,duration_days:days,offered_value:r.offered.estimated_value||0,requested_value:r.requested.estimated_value||0,proposed_deposit:0,message:msg||null});if(error){alert(error.message);return}alert('Exchange request sent. The other collector must accept it before an exchange is created.');if(window.bc22Nav)window.bc22Nav('requests');};
window.bc22Msg=async id=>{if(window.bc22Chat)window.bc22Chat(id,'');else alert('Open Messages to contact this collector.')};
const old=window.bcNav;window.bcNav=p=>{if(p==='matches')return matchesPage();return old?old(p):null};window.bc22Nav=p=>{if(p==='matches')return matchesPage();return old?old(p):null};
if(location.hash==='#matches')setTimeout(matchesPage,250);
})();