(()=>{
const U='https://nsxtromjdpdscknadxez.supabase.co',K='sb_publishable_JJhVbgJblHrnKuPOsJkxQ_zRoQNlIL';
const db=window.supabase.createClient(U,K);const oldNav=window.bc22Nav;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const style=document.createElement('style');style.textContent='.bc22reviews{display:grid;gap:12px}.bc22reviewrow{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.bc22stars button{border:0;background:transparent;font-size:28px;cursor:pointer;padding:2px}.bc22stars button.off{opacity:.35}.bc22reviews textarea{width:100%;min-height:90px;padding:10px;border:1px solid #d9dee7;border-radius:9px;font:inherit}.bc22reviews .primary{border:1px solid #111827;background:#111827;color:#fff;border-radius:9px;padding:9px 12px;font-weight:750;cursor:pointer}';document.head.appendChild(style);
async function reviews(){const {data:{user}}=await db.auth.getUser();const app=document.querySelector('#app');if(!app||!user){if(window.bcAuth)window.bcAuth();return}
 const {data:exchanges,error}=await db.from('exchanges').select('*').or(`user_a.eq.${user.id},user_b.eq.${user.id}`).eq('state','completed').order('completed_at',{ascending:false});
 if(error){app.innerHTML='<div class="wrap"><div class="v22notice">Unable to load completed exchanges.</div></div>';return}
 const ids=(exchanges||[]).map(e=>e.id);let reviewed=new Set();if(ids.length){const {data:rv}=await db.from('reviews').select('exchange_id,reviewer_id').in('exchange_id',ids).eq('reviewer_id',user.id);(rv||[]).forEach(x=>reviewed.add(x.exchange_id))}
 app.innerHTML=`<div class="wrap"><div class="v22nav"><button onclick="bc22Nav('home')">Home</button><button class="on">Reviews</button><button onclick="bc22Nav('exchanges')">My Exchanges</button></div><div class="xcard"><h2>Collector reviews</h2><p class="xmuted">Review your exchange partner after a completed swap. One review per person per exchange.</p></div><div style="height:14px"></div><div class="bc22reviews">${(exchanges||[]).map(e=>{const other=e.user_a===user.id?e.user_b:e.user_a;return `<div class="xcard"><h3>Completed exchange</h3><p class="xmuted">Partner: <span data-person="${other}">Collector</span> · ${new Date(e.completed_at||e.updated_at).toLocaleDateString()}</p>${reviewed.has(e.id)?'<div class="xnotice">You have already reviewed this collector.</div>':`<form onsubmit="bc22SubmitReview(event,'${e.id}','${other}')"><div class="bc22reviewrow"><b>Rating</b><span class="bc22stars" data-stars="${e.id}">${[1,2,3,4,5].map(n=>`<button type="button" class="off" onclick="bc22Star('${e.id}',${n})">★</button>`).join('')}</span></div><input type="hidden" id="rating-${e.id}" value="5"><textarea id="comment-${e.id}" maxlength="1000" placeholder="How was your exchange experience?"></textarea><button class="primary" type="submit">Submit review</button></form>`}</div>`}).join('')||'<div class="xnotice">Complete an exchange to leave your first review.</div>'}</div></div>`;
 const partnerIds=[...new Set((exchanges||[]).map(e=>e.user_a===user.id?e.user_b:e.user_a))];if(partnerIds.length){const {data:p}=await db.from('profiles').select('id,display_name').in('id',partnerIds);(p||[]).forEach(x=>document.querySelector(`[data-person="${x.id}"]`)?.replaceChildren(document.createTextNode(x.display_name||'Collector')))}
}
window.bc22Star=(id,n)=>{const h=document.querySelector(`[data-stars="${id}"]`);if(!h)return;h.querySelectorAll('button').forEach((b,i)=>b.classList.toggle('off',i>=n));const el=document.querySelector(`#rating-${id}`);if(el)el.value=n};
window.bc22SubmitReview=async(ev,id,other)=>{ev.preventDefault();const rating=Number(document.querySelector(`#rating-${id}`).value||5),comment=document.querySelector(`#comment-${id}`).value;const {error}=await db.rpc('submit_exchange_review',{p_exchange_id:id,p_rating:rating,p_comment:comment});if(error)return alert(error.message);alert('Review submitted. Thank you!');reviews()};
const inject=()=>{const n=document.querySelector('.xnav');if(n&&!n.querySelector('[data-reviews-nav]')){const b=document.createElement('button');b.textContent='Reviews';b.dataset.reviewsNav='1';b.onclick=()=>window.bc22Nav('reviews');n.appendChild(b)}};
const mo=new MutationObserver(inject);mo.observe(document.body,{childList:true,subtree:true});
const prev=window.bc22Nav;window.bc22Nav=(p)=>{if(p==='reviews'){location.hash='reviews';reviews()}else prev(p)};
if(location.hash==='#reviews')reviews();
})();
