/* BrickCircle V2.4 — temporary swap return workflow */
(()=>{
  const U='https://nsxtromjdpdscknadxez.supabase.co',K='sb_publishable_JJhVbgjGblHrnKuPOsJkxQ_zRoQNlIL';
  const db=window.supabase.createClient(U,K),root=()=>document.querySelector('#app');
  const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let user=null,ex=[],ret=[],profiles={};
  const css=`.bc24{max-width:1180px;margin:auto;padding:24px 18px 80px}.bc24-hero{background:linear-gradient(135deg,#111827,#23385d);color:#fff;padding:26px;border-radius:22px;margin-bottom:16px}.bc24-hero h1{margin:0 0 8px;font-size:34px}.bc24-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.bc24-card{background:#fff;border:1px solid #e5e7eb;border-radius:18px;padding:20px;box-shadow:0 8px 25px #1118270b}.bc24-due{padding:12px 14px;border-radius:12px;background:#fff8db;border:1px solid #f3dc83;margin:12px 0}.bc24-due.overdue{background:#fff1f2;border-color:#fda4af;color:#9f1239}.bc24-alert{padding:12px 14px;border-radius:12px;background:#fff1f2;border:1px solid #fecdd3;color:#9f1239;margin:12px 0}.bc24-step{padding:12px;border:1px solid #e5e7eb;border-radius:12px;margin-top:9px}.bc24-step.ok{background:#ecfdf3;border-color:#a6f4c5}.bc24-step.lock{background:#f8fafc;color:#667085}.bc24-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:11px}.bc24 button{min-height:44px;border:1px solid #d0d5dd;border-radius:10px;padding:10px 14px;background:#fff;font-weight:800}.bc24 button.primary{background:#111827;color:#fff}.bc24 button.danger{background:#9f1239;color:#fff;border-color:#9f1239}.bc24small{font-size:12px;color:#667085}.bc24-empty{padding:26px;background:#fff;border:1px solid #e5e7eb;border-radius:18px}@media(max-width:760px){.bc24-grid{grid-template-columns:1fr}.bc24{padding:14px 12px 90px}.bc24-hero{padding:20px}.bc24-hero h1{font-size:28px}.bc24-actions button{width:100%}}`;
  function style(){if(document.getElementById('bc24style'))return;let s=document.createElement('style');s.id='bc24style';s.textContent=css;document.head.appendChild(s)}
  async function load(){
    user=(await db.auth.getUser()).data.user;if(!user)return;
    await db.rpc('check_my_overdue_returns').catch(()=>{});
    let q=await db.from('exchanges').select('*').or(`user_a.eq.${user.id},user_b.eq.${user.id}`).eq('state','swap_active').order('return_due_at',{ascending:true});ex=q.data||[];
    ret=[];profiles={};
    if(ex.length){let rr=await db.from('exchange_returns').select('*').in('exchange_id',ex.map(x=>x.id));ret=rr.data||[];let ids=[...new Set(ex.flatMap(x=>[x.user_a,x.user_b]))];let p=await db.from('profiles').select('id,display_name,city,country').in('id',ids);(p.data||[]).forEach(x=>profiles[x.id]=x)}
  }
  const R=id=>ret.find(x=>x.exchange_id===id),mine=(e,k)=>{let r=R(e.id),a=user.id===e.user_a;return r?.[k+(a?'_a':'_b')]},other=(e,k)=>{let r=R(e.id),a=user.id===e.user_a;return r?.[k+(a?'_b':'_a')]};
  function steps(e,r){const bothSafe=r.safety_ack_a&&r.safety_ack_b,bothArrived=r.arrived_a&&r.arrived_b,bothInspected=r.inspected_a&&r.inspected_b;let rows=[['safety_ack','I agree to the Safe Return Meetup rules',true,''],['arrived','I have arrived for the return',bothSafe,'Both collectors must accept the return meetup rules first.'],['inspected','I inspected my returned LEGO set',bothArrived,'Inspection unlocks only after both collectors confirm arrival.'],['confirm','I received my LEGO set back satisfactorily',bothInspected,'Final confirmation unlocks only after both returned sets are inspected.']];return rows.map(([a,l,open,why])=>{let k=a==='confirm'?'confirmed':a,yes=mine(e,k),them=other(e,k);return `<div class="bc24-step ${yes?'ok':''} ${!open&&!yes?'lock':''}"><b>${yes?'✓ ':''}${l}</b><div class="bc24small">Other collector: ${them?'✓ confirmed':'waiting'}</div>${!yes&&open?`<div class="bc24-actions"><button onclick="bc24Act('${e.id}','${a}')">Confirm</button></div>`:''}${!open&&!yes?`<div class="bc24small">🔒 ${why}</div>`:''}</div>`}).join('')+`<div class="bc24-actions"><button onclick="bc24Issue('${e.id}')">Report return issue</button></div>`}
  function card(e){let r=R(e.id),oid=user.id===e.user_a?e.user_b:e.user_a,p=profiles[oid]||{},due=e.return_due_at?new Date(e.return_due_at):null,days=due?Math.ceil((due-Date.now())/86400000):null,overdue=days!==null&&days<0;let dueText=due?due.toLocaleString():'Return date pending';return `<section class="bc24-card"><h2>Return swap with ${esc(p.display_name||'Collector')}</h2><div>${esc(p.city||'')} ${esc(p.country||'')}</div><div class="bc24-due ${overdue?'overdue':''}"><b>${overdue?'⚠ Return overdue:':'Return due:'}</b> ${esc(dueText)}${days!==null?`<div class="bc24small">${days>=0?days+' day'+(days===1?'':'s')+' remaining':Math.abs(days)+' day'+(Math.abs(days)===1?'':'s')+' overdue'}</div>`:''}</div>${overdue?`<div class="bc24-alert"><b>Action needed</b><br>Message the other collector and arrange the return as soon as possible. If the return cannot be resolved, report an overdue-return issue so the swap is formally paused.</div>`:''}${r?`<p><b>Venue:</b> ${esc(r.venue_name||'')} ${r.venue_area?'· '+esc(r.venue_area):''}<br><b>Time:</b> ${r.meetup_at?esc(new Date(r.meetup_at).toLocaleString()):'Not set'}</p>`:'<p class="bc24small">Schedule a public meetup to return the temporarily swapped LEGO sets.</p>'}<div class="bc24-actions"><button class="primary" onclick="bc24Schedule('${e.id}')">${r?'Reschedule return':'Schedule return'}</button>${window.bc22Chat?`<button onclick="bc22Chat('${oid}','${e.id}')">Message collector</button>`:''}${overdue?`<button class="danger" onclick="bc24Overdue('${e.id}')">Report overdue return</button>`:''}</div>${r?steps(e,r):''}</section>`}
  async function page(){await load();if(!user){window.bcAuth?.();return}style();root().innerHTML=`<div class="bc24"><div class="bc24-hero"><h1>Return LEGO Sets</h1><p>Your temporary swap remains active until both collectors meet again, inspect their returned sets and confirm the return together.</p></div><div class="bc24-grid">${ex.length?ex.map(card).join(''):'<div class="bc24-empty"><h3>No active returns</h3><p>When a temporary 30/60/90-day swap is underway, its return date and return meetup workflow will appear here.</p></div>'}</div></div>`}
  function sheet(id){let old=document.getElementById('bc24sheet');old?.remove();let el=document.createElement('div');el.id='bc24sheet';el.style.cssText='position:fixed;inset:0;background:#0007;z-index:9999;display:flex;align-items:flex-end;justify-content:center';el.innerHTML=`<div style="background:#fff;width:min(620px,100%);border-radius:20px 20px 0 0;padding:20px;padding-bottom:calc(20px + env(safe-area-inset-bottom));max-height:85vh;overflow:auto"><h3 style="margin-top:0">Schedule return meetup</h3><label>Public venue<input id="bc24venue" style="width:100%;font-size:16px;padding:12px;margin:6px 0 12px" placeholder="Café, mall, hobby store"></label><label>Area / neighbourhood<input id="bc24area" style="width:100%;font-size:16px;padding:12px;margin:6px 0 12px"></label><label>Date & time<input id="bc24when" type="datetime-local" style="width:100%;font-size:16px;padding:12px;margin:6px 0 16px"></label><div style="display:flex;gap:8px"><button style="flex:1;min-height:48px" onclick="document.getElementById('bc24sheet').remove()">Cancel</button><button style="flex:1;min-height:48px;background:#111827;color:#fff" onclick="bc24Save('${id}')">Save return meetup</button></div></div>`;document.body.appendChild(el)}
  window.bc24Schedule=sheet;
  window.bc24Save=async id=>{let v=document.getElementById('bc24venue').value.trim(),a=document.getElementById('bc24area').value.trim(),w=document.getElementById('bc24when').value;if(!v||!w){alert('Enter a public venue and return date/time.');return}let d=new Date(w);if(isNaN(d)){alert('Choose a valid date and time.');return}let {error}=await db.rpc('setup_return_meetup',{p_exchange_id:id,p_venue_name:v,p_venue_area:a||null,p_meetup_at:d.toISOString()});if(error)alert(error.message);else{document.getElementById('bc24sheet')?.remove();page()}};
  window.bc24Act=async(id,a)=>{if(a==='confirm'&&!confirm('Confirm only after your own LEGO set has been returned and inspected. Continue?'))return;let {error}=await db.rpc('return_action',{p_exchange_id:id,p_action:a,p_note:null});if(error)alert(error.message);else page()};
  window.bc24Issue=async id=>{let note=prompt('Describe the return problem (damage, missing pieces, wrong set, etc.).');if(!note)return;let {error}=await db.rpc('return_action',{p_exchange_id:id,p_action:'issue',p_note:note});if(error)alert(error.message);else{alert('The return has been paused and marked as disputed.');location.hash='profile'}};
  window.bc24Overdue=async id=>{let note=prompt('Briefly describe the overdue return / no-show problem.');if(note===null)return;let {error}=await db.rpc('report_overdue_return_issue',{p_exchange_id:id,p_note:note||'Return overdue / no-show'});if(error)alert(error.message);else{alert('The overdue return has been marked as disputed and paused for resolution.');location.hash='profile'}};
  const old=window.bcNav;window.bcNav=p=>{if(p==='returns'){location.hash='returns';return page()}return old?.(p)};
  window.addEventListener('hashchange',()=>{if(location.hash==='#returns')page()});window.addEventListener('focus',()=>{if(location.hash==='#returns')page()});if(location.hash==='#returns')setTimeout(page,200);
})();
